[2023-06-30T09:51:39.800+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: BigData_Pipeline.store_data_in_gcs_task manual__2023-06-30T09:51:26+00:00 [queued]>
[2023-06-30T09:51:39.809+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: BigData_Pipeline.store_data_in_gcs_task manual__2023-06-30T09:51:26+00:00 [queued]>
[2023-06-30T09:51:39.809+0000] {taskinstance.py:1308} INFO - Starting attempt 1 of 1
[2023-06-30T09:51:39.824+0000] {taskinstance.py:1327} INFO - Executing <Task(PythonOperator): store_data_in_gcs_task> on 2023-06-30 09:51:26+00:00
[2023-06-30T09:51:39.829+0000] {standard_task_runner.py:57} INFO - Started process 3589 to run task
[2023-06-30T09:51:39.833+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'BigData_Pipeline', 'store_data_in_gcs_task', 'manual__2023-06-30T09:51:26+00:00', '--job-id', '21', '--raw', '--subdir', 'DAGS_FOLDER/main.py', '--cfg-path', '/tmp/tmp7ymx5e5r']
[2023-06-30T09:51:39.834+0000] {standard_task_runner.py:85} INFO - Job 21: Subtask store_data_in_gcs_task
[2023-06-30T09:51:39.850+0000] {logging_mixin.py:149} WARNING - /home/***/.local/lib/python3.7/site-packages/***/settings.py:195 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2023-06-30T09:51:39.892+0000] {task_command.py:410} INFO - Running <TaskInstance: BigData_Pipeline.store_data_in_gcs_task manual__2023-06-30T09:51:26+00:00 [running]> on host 656f1a73f746
[2023-06-30T09:51:39.987+0000] {taskinstance.py:1547} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='BigData_Pipeline' AIRFLOW_CTX_TASK_ID='store_data_in_gcs_task' AIRFLOW_CTX_EXECUTION_DATE='2023-06-30T09:51:26+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-06-30T09:51:26+00:00'
[2023-06-30T09:51:40.553+0000] {logging_mixin.py:149} INFO - Data loaded to Google Cloud Storage: Company not found:2015
[2023-06-30T09:51:40.568+0000] {python.py:183} INFO - Done. Returned value was: None
[2023-06-30T09:51:40.577+0000] {taskinstance.py:1350} INFO - Marking task as SUCCESS. dag_id=BigData_Pipeline, task_id=store_data_in_gcs_task, execution_date=20230630T095126, start_date=20230630T095139, end_date=20230630T095140
[2023-06-30T09:51:40.606+0000] {local_task_job_runner.py:225} INFO - Task exited with return code 0
[2023-06-30T09:51:40.630+0000] {taskinstance.py:2651} INFO - 1 downstream tasks scheduled from follow-on schedule check
